version: "3"
# SPDX-FileCopyrightText: 2022-present Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  mininet:
    build:
      context: mininet
      args:
        - DBUF_IMAGE=${DBUF_IMAGE}
        - MN_STRATUM_IMAGE=${MN_STRATUM_IMAGE}
    platform: linux/amd64
    hostname: mininet
    container_name: mininet
    privileged: true
    tty: true
    stdin_open: true
    entrypoint: "/mininet/entrypoint.sh"
    volumes:
      - ./tmp:/tmp
      - ./mininet:/mininet
    expose:
      - 50001 # leaf1
      - 50002 # leaf2
      - 50003 # spine1
      - 50004 # spine2
    environment:
      - MN_SCRIPT=/mininet/topo-${TOPO}.py
  onos1:
    # Tost image comes with latest trellis apps
    image: ${ONOS_IMAGE}
    platform: linux/amd64
    hostname: onos1
    container_name: onos1
    ports:
      - "8181:8181" # HTTP
      - "8101:8101" # SSH (CLI)
      - "51001:51001" # UP4 app's P4Runtime server
      - "5005:5005" # Java debugger
    volumes:
      - ./tmp/onos1:/root/onos/apache-karaf-4.2.14/data/tmp
    env_file:
      - .env # Includes ONOS_APPS
    entrypoint: "./bin/onos-service"
    command: [ "debug" ]

  # P4-UPF services
  pfcp-agent:
    profiles:
      - upf
    image: ${PFCP_AGENT_IMAGE}
    platform: linux/amd64
    hostname: pfcp-agent
    container_name: pfcp-agent
    tty: true
    stdin_open: true
    volumes:
      - ./tmp:/tmp
      - ./config/pfcp-agent.json:/config.json
    entrypoint: "/bin/pfcpiface"
    command: [ "-config", "/config.json" ]
    working_dir: /bin/
    expose:
      - 8805 # PFCP
    ports:
      - "8080:8080" # HTTP: REST API for slice meter configuration
  smf-sim:
    profiles:
      - upf
    image: ${PFCPSIM_IMAGE}
    platform: linux/amd64
    hostname: smf-sim
    container_name: smf-sim
    tty: true
    volumes:
      - ./tmp:/tmp
      - ./topo:/topo
      - ./bin:/up4/bin
