# SPDX-FileCopyrightText: 2022-present Intel Corporation
# SPDX-License-Identifier: Apache-2.0

FROM python:3.9.0-slim-buster
RUN pip3 install --no-cache-dir \
    p4runtime-shell scapy==2.4.5

ENV PATH=/up4/bin:${PATH}
