# Copyright 2022-present Open Networking Foundation
# SPDX-License-Identifier: Apache-2.0

---
name: REUSE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: reuse lint
        uses: fsfe/reuse-action@v1
